# Generated by Django 4.1.1 on 2022-09-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmaster',
            name='cnic',
            field=models.CharField(max_length=200),
        ),
    ]
